# Cos'è NumPy?
### Da Wikipedia: "NumPy è una libreria open source per il linguaggio di programmazione Python, che aggiunge supporto a grandi matrici e array multidimensionali insieme a una vasta collezione di funzioni matematiche di alto livello per poter operare efficientemente su queste strutture dati."

### NumPy ci consente di lavorare con gli array (simili alle liste, ma 50 volte più veloci).

### Per maggiori info: https://www.w3schools.com/python/numpy/numpy_intro.asp

In [1]:
# Importare la libreria "NumPy"
import numpy as np

# Sezioni del notebook:
1. ### Creare arrays con NumPy
2. ### In cosa differiscono arrays e liste?
3. ### Indicizzare un array
4. ### Slicing di un array
5. ### Tipi di dati che un array può contenere
6. ### View e Copy
7. ### Shape, Reshape e Flatten
8. ### Iterare un array
9. ### Unire due array
10. ### Dividere un array
11. ### Cercare, filtrare, ordinare
12. ### Creare un array contenente dati randomici
13. ### ufunc: definire una funzione personalizzata

## 1. Creare arrays con NumPy

In [2]:
# Creare un array di 0 dimensioni (scalare)

arr = np.array(42)
print(arr)
print("dimensioni: " + str(arr.ndim))

42
dimensioni: 0


In [3]:
# Creare un array di 1 dimensioni (vettore)

arr = np.array([1,2,3])
print(arr)
print("dimensioni: " + str(arr.ndim))

[1 2 3]
dimensioni: 1


In [4]:
# Creare un array di 2 dimensioni (array di array)

arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)
print("dimensioni: " + str(arr.ndim))

[[1 2 3]
 [4 5 6]]
dimensioni: 2


In [5]:
# Creare un array di N dimensioni (array di array di array ...)

arr = np.array([1,2,3], ndmin = 5)
print(arr)
print("dimensioni: " + str(arr.ndim))

[[[[[1 2 3]]]]]
dimensioni: 5


### Il metodo ".arange()" ci consente di popolare un array in modo automatico. Nello specifico, ci consente di creare un array contenente valori che partono da A e arrivano a B, procedendo di uno step C.

In [6]:
# Usando ".arange()", creare un array che parte da 5 e arriva a 20 (compreso) con uno step di 3

arr = np.arange(5, 20+1, 3)
print(arr)

[ 5  8 11 14 17 20]


### Il metodo .zeros() consente di creare un array contenente solo degli 0 (utile per inizializzare un contatore, ad esempio)

In [7]:
# Creare un array di 1 dimensione contenente solo zeri

arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [8]:
# Creare un array di 2 dimensione contenente solo zeri

arr = np.zeros((5,2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [9]:
# Creare un array di 3 dimensione contenente solo zeri

arr = np.zeros((5,2,3))
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


### Il metodo .ones() consente di creare un array contenente solo degli 1

In [10]:
# Creare un array di 1 dimensione contenente solo uno

arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [11]:
# Creare un array di 2 dimensione contenente solo uno

arr = np.ones((5,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
# Creare un array di 3 dimensione contenente solo uno

arr = np.ones((5,2,3))
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


## 2. In cosa differiscono arrays e liste?

In [13]:
# Creare un array NumPy
a = np.array([1,2,3,4,5])

# Creare una lista
l = [1,2,3,4,5]

print(a)
print(l)

[1 2 3 4 5]
[1, 2, 3, 4, 5]


### Una prima fondamentale differenza è che possiamo eseguire operazioni matematiche sugli array molto più facilmente di quanto non riusciamo a fare sulle liste.

In [14]:
# Operazioni su liste
print(l*5)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


### Invece di ottenere ogni elemento della lista moltiplicto per 5, abbiamo ottenuto la lista ripetuta per 5 molte di fila. Vediamo cosa succede con gli array.

In [15]:
# Operazioni su array
print(a*5)

[ 5 10 15 20 25]


### In questo caso abbiato ottenuto ogni elemento dell'array moltiplicato per 5, proprio il risultato da noi desiderato. Come mostrerò in seguito, è possibile eseguire ogni possibile operazione sugli array (sulle liste, somme e sottrazioni restituirebbero un errore).

In [16]:
# Somma su array
print(a+1)

# Sottrazione su array
print(a-1)

[2 3 4 5 6]
[0 1 2 3 4]


## 3. Indicizzare un array

### Molto semplicemente, "indicizzare un array" significa essere in grado di prendere l'elemento di nostro interesse riferendoci agli indici che ne specificano la posizione.

In [17]:
# Indicizzare un array ad 1 dimensione - Prendere l'elemento "b"

arr = np.array(["a", "b", "c"])
print(arr[1])

b


In [18]:
# Indicizzare un array a 2 dimensioni - Prendere l'elemento "d"

arr = np.array([["a", "b", "c"],
                ["d", "e", "f"]])
print(arr[1,0])

d


In [19]:
# Indicizzare un array a 3 dimensioni - Prendere l'elemento "c"

arr = np.array([ [ ["a", "b", "c"],
                   ["d", "e", "f"] ],
                 [ ["a", "b", "c"],
                   ["d", "e", "f"] ]
               ])
print(arr[1,0,2])

c


### Approfondimento sull'indicizzazione di un array a 3 dimensioni: considerando che si parte a contare da 0, "1" indica "concentriamoci sulla seconda lista di array", "0" indica "concentriamoci sul primo array della seconda lista di array" ed infine "2" indica "concentriamoci sul terzo elemento del primo array della seconda lista di array".

### E' possibile indicizzare anche con numeri negativi: "-1" significa "ultimo elemento", "-2" significa penultimo elemento ecc.

In [20]:
# Indicizzare negativamente un array ad 1 dimensione - prendere l'ultimo elemento

arr = np.array(["a", "b", "c"])
print(arr[-1])

c


In [21]:
# Indicizzare negativamente un array a 2 dimensioni - prendere il penultimo elemento dell'ultimo array

arr = np.array([["a", "b", "c"],
                ["d", "e", "f"]])
print(arr[-1,-2])

e


## 4. Slicing di un array

### Eseguire lo slicing di un array serve per prendere solo una parte degli elementi dell'array stesso.

### 4.1 Slicing di array ad 1 dimensione

In [22]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)

# Prendere i numeri dal 4 al 7
print(a[3:7])

# Prendere i numeri dal 4 in poi
print(a[3:])

# Prendere i numeri fino al 4
print(a[:4])

# Prendere tutti i numeri, escluso l'ultimo
print(a[:-1])

# Prendere i numeri dal 2 al 7, uno si ed uno no (step)
print(a[1:7:2])

[1 2 3 4 5 6 7 8]
[4 5 6 7]
[4 5 6 7 8]
[1 2 3 4]
[1 2 3 4 5 6 7]
[2 4 6]


### 4.2 Slicing di array a 2 dimensioni

In [23]:
a = np.array([
                [1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]
             ])
print(a)

# Prendere i numeri 10 ed 11
print(a[2,1:3])

# Prendere la sotto-matrice composta da 1,2,5,6
print(a[0:2,0:2])

# Prendere un numero si ed un numero no dal secondo dei 3 array (step)
print(a[1,::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 11]
[[1 2]
 [5 6]]
[5 7]


### Scrivendo "::" stiamo dicendo di prendere tutti gli elementi dell'array. Segue poi il 2 ad indicare lo step.

## 5. Tipi di dati che un array può contenere

### Per una panoramica completa sui tipi di dati che NumPy consente di gestire, guarda qui: https://www.w3schools.com/python/numpy/numpy_data_types.asp

In [24]:
# Controllare il tipo di dati contenuti in un array

arr = np.array([1,2,3])
print(arr.dtype)

arr = np.array([1.4,2.1,3.7])
print(arr.dtype)

arr = np.array([True, True, False])
print(arr.dtype)

int64
float64
bool


In [25]:
# Creare un array contenente stringhe

arr = np.array([2,3,4], dtype="S")
print(arr.dtype)

|S1


In [26]:
# Creare un array contenente int

arr = np.array(['2','3','4'], dtype="i")
print(arr.dtype)

int32


### "S" sta per stringa. "i" sta per integer. Trovi tutte le associazioni "tipo/codice" nel link riportato ad inizio sessione.

In [27]:
# Convertire un array contenente int in un array contenente float

arr = np.array([2,3,4])
print(arr.dtype)

arr = arr.astype('f')
print(arr.dtype)

int64
float32


## 6. View e Copy

### Sia View che Copy servono a copiare il contenuto di un array in un altro array. Differiscono poiché:
* ### Se uso "Copy" per copiare A in B, modificando B non modifico A. 
* ### Se uso "View" per copiare A in B, modificando B modifico anche A.

In [28]:
# Esempio con "copy"

arr = np.array([1,2,3])
copia = arr.copy()
print(arr)
print(copia)
print("Base: " + str(copia.base))

[1 2 3]
[1 2 3]
Base: None


In [29]:
copia[0] = 5
print(arr)
print(copia)

[1 2 3]
[5 2 3]


### In questo primo esempio usiamo "copy". Modificando l'array "copia", l'array originale "arr" non è cambiato. "copia" non ha una base poiché è un array a se stante.

In [30]:
# Esempio con "view"

arr = np.array([1,2,3])
copia = arr.view()
print(arr)
print(copia)
print("Base: " + str(copia.base))

[1 2 3]
[1 2 3]
Base: [1 2 3]


In [31]:
copia[0] = 5
print(arr)
print("Base: " + str(copia.base))

[5 2 3]
Base: [5 2 3]


### In questo secondo esempio usiamo "view". Modificando l'array "copia", l'array originale "arr" è cambiato. "copia" ha una base poiché non è un array a se stante.

## 7. Shape, Reshape e Flatten

### Shape ci consente di ricavare informazioni sulle dimensioni di un array. Reshape ci consente di modificare le dimensioni di un array, compatibilmente col suo numero di elementi. Flatten ci consente di partire da un array ad N dimensioni e di creare un vettore uni-dimensionale contenente tutti i suoi elementi in fila.

In [32]:
# Usare "shape" per ricavare le dimensioni di un array.

arr = np.array([1,2,3,4])
print(arr.shape)

arr = np.array([[1,2,3,4],[9,8,7,6]])
print(arr.shape)

(4,)
(2, 4)


In [33]:
# Usare "reshape" per modificare le dimensioni di un array

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(2,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [34]:
# Usare "reshape" per modificare le dimensioni di un array

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
# Usare "reshape" per modificare le dimensioni di un array

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(3,2,2))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


### Se volessimo un 2x2xN ma non conoscessimo N? N è una dimensione ignota e la possiamo gestire utilizzando "-1". La corretta dimensione verrà calcolata automaticamente da NumPy. Possiamo avere una dimensione ignota alla volta, mai più di una.

In [36]:
# Usare "reshape" per modificare le dimensioni di un array con dimensione ignota

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(2,2,-1))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [37]:
# Usare "flatten" per appiattire un array multidimensionale

arr = np.array([[1,2],[3,4]])
print(arr.flatten())

[1 2 3 4]


### Lo stesso identico risultato si può ottenere con ".reshape(-1)".

In [38]:
# Usare "reshape(-1)" per appiattire un array multidimensionale

arr = np.array([[1,2],[3,4]])
print(arr.reshape(-1))

[1 2 3 4]


## 8. Iterare un array

### "Iterare un array" significa semplicemente passare uno ad uno tutti i suoi elementi.

In [39]:
# Iterare un array ad 1 dimensione

arr = np.array([1,2,3,4,5,6,7,8])
for x in arr:
    print("Ecco l'elemento: " +  str(x))

Ecco l'elemento: 1
Ecco l'elemento: 2
Ecco l'elemento: 3
Ecco l'elemento: 4
Ecco l'elemento: 5
Ecco l'elemento: 6
Ecco l'elemento: 7
Ecco l'elemento: 8


In [40]:
# Iterare un array a 2 dimensioni

arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in arr:
    print("Ecco l'elemento: " +  str(x))

Ecco l'elemento: [1 2 3 4]
Ecco l'elemento: [5 6 7 8]


### Come vedi, invece di ottenere i singoli elementi (1,2,3 ...) abbiamo ottenuto gli array contenuti nell'array più esterno. Per ottenere i singoli elementi ci serve un secondo ciclo for.

In [41]:
# Iterare un array a 2 dimensioni

arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in arr:
    for y in x:
        print("Ecco l'elemento: " +  str(y))

Ecco l'elemento: 1
Ecco l'elemento: 2
Ecco l'elemento: 3
Ecco l'elemento: 4
Ecco l'elemento: 5
Ecco l'elemento: 6
Ecco l'elemento: 7
Ecco l'elemento: 8


### Un approccio simile a questo può funzionare anche con 3, 4 ... N dimensioni. Il problema è che se aumenta il numero di dimensioni aumenta anche il numero di cicli for necessari: il codice risulterà molto complesso.
### Per evitare di utilizzare N cicli for, possiamo utilizzare "nditer" che ci consente di andare a leggere i singoli elementi di ogni array ad ogni dimensione.

In [42]:
# Iterare un array a 2 dimensioni con nditer

arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr):
    print("Ecco l'elemento: " +  str(x))

Ecco l'elemento: 1
Ecco l'elemento: 2
Ecco l'elemento: 3
Ecco l'elemento: 4
Ecco l'elemento: 5
Ecco l'elemento: 6
Ecco l'elemento: 7
Ecco l'elemento: 8


### Iterare tutti gli elementi di un array può essere comodo, ad esempio, per cambiare il tipo di dati.

In [43]:
# Modificare il tipo degli elementi in un array usando nditer

arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr, flags=["buffered"], op_dtypes = ["S"]):
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


### E' possibile fare slicing all'interno di nditer per iterare solo su alcuni elementi.

In [44]:
# Usare nditer + slicing per iterare su un elemento si e su un elemento no

arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


### Se oltre all'elemento ci interessa anche la sua posizione (l'indice), usiamo ndenumerate invece di nditer.

In [45]:
# Usare nditer per iterare su un elemento si e su un elemento no

arr = np.array([[11,12,13,14],[15,16,17,18]])
for idx, x in np.ndenumerate(arr[:,::2]):
    print(str(idx) + ": " + str(x))

(0, 0): 11
(0, 1): 13
(1, 0): 15
(1, 1): 17


## 9. Unire due array

### Per unire due array possiamo utilizzare "concatenate" o "stack". Questi due metodi lavorano in modo diverso. Vediamoli all'azione.

In [46]:
# Concatenare due array di 1 dimensione usando "concatenate"

arr1 = np.array([1,2,3])
arr2 = np.array([5,6,7])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 5 6 7]


In [47]:
# Concatenare due array di 2 dimensioni usando "concatenate"

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
arr = np.concatenate((arr1,arr2))
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### I due array sono stati concatenati sulla prima dimensione (elemento N+1 alla destra dell'elemento N). Questo perché in "concatenate" è implicito "axis=0". Possiamo invece concatenare sulla seconda dimensione (verticalmente) specificando "axis=1".

In [48]:
# Concatenare due array di 2 dimensioni sull
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
arr = np.concatenate((arr1,arr2), axis = 1)
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### Vediamo ora come si comporta "stack".

In [49]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr_conc = np.concatenate((arr1,arr2))
arr_stack = np.stack((arr1,arr2))

print(arr_conc)
print(arr_stack)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


### Dati i due array di partenza, "concatenate" crea un singolo array mettendo gli elementi del secondo array alla destra degli elementi del primo, "stack", invece, mette i due array uno sopra l'altro, impilandoli verticalmente. 

### Anche per "stack", l'asse di default è l'asse 0, ma è possibile specificare axis = 1 per impilare diversamente gli array (invece di mettere gli array "uno sopra l'altro", li mettiamo "uno accanto all'altro").

In [50]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr_stack = np.stack((arr1,arr2), axis=1)

print(arr_stack)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


### Esistono due varianti di "stack", "vstack" e "hstack". Vediamone il funzionamento.

In [51]:
# vstack equivale a stack con axis = 0

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr_stack = np.vstack((arr1,arr2))

print(arr_stack)

[[1 2 3 4]
 [5 6 7 8]]


In [52]:
# dstack equivale a stack con axis = 1 

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr_stack = np.dstack((arr1,arr2))

print(arr_stack)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


## 10. Dividere un array

### Per spezzare un array possiamo utilizzare "array_split" o "split". I due metodi funzionano poiché "array_split" funziona anche in caso di divisioni non perfette mentre "split" funziona solo in caso di divisioni perfette. Vediamo come.

In [53]:
# array_split: divide l'array in n parti uguali

arr = np.array([1,2,3,4,5,6,7,8])
print(np.array_split(arr,2))
print(np.array_split(arr,4))

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [54]:
# array_split: esempio di divisione non perfetta

arr = np.array([1,2,3,4,5,6,7,8])
print(np.array_split(arr,3))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [55]:
# split: divide l'array in n parti uguali

arr = np.array([1,2,3,4,5,6,7,8])
print(np.split(arr,4))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [57]:
# split: esempio di divisione non perfetta
arr = np.array([1,2,3,4,5,6,7,8])
print(np.split(arr,3))

ValueError: array split does not result in an equal division

### E' possibile splittare anche array di più dimensioni.

In [ ]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
print(np.split(arr,2))

### Da notare che il numero di dimensioni viene mantenuto. E' possibile splittare anche sull'asse 1, eseguendo una divisione "verticale". 

In [58]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
print(np.split(arr, 2, axis=1))

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


### Esistono due varianti di "split", "vsplit" e "hsplit". Vediamone il funzionamento.

In [59]:
# vsplit equivale ad uno split sull'asse 0

arr = np.array([[1,2],[3,4],[5,6],[7,8]])
print(np.split(arr, 2, axis=0))
print(np.vsplit(arr,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [60]:
# hsplit equivale ad uno split sull'asse 0

arr = np.array([[1,2],[3,4],[5,6],[7,8]])
print(np.split(arr, 2, axis=1))
print(np.hsplit(arr,2))

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


## 11. Cercare, filtrare, ordinare

### Per cercare un array si utilizza il metodo "where", che ci restituisce le posizioni nell'array degli elementi trovati.

In [61]:
# Cercare elementi usando "where"

arr = np.array([1,2,3,4,3,6,7,3])
print(np.where(arr == 3))
print(np.where(arr == 10))

(array([2, 4, 7]),)
(array([], dtype=int64),)


### E' anche possibile usare "where" specificando un filtro, un criterio di ricerca

In [62]:
# Cercare i numeri pari

arr = np.array([1,2,3,4,3,6,7,3])
print(np.where(arr%2 == 0))

(array([1, 3, 5]),)


### Per ordinare un array si usa il metodo sort. 

In [63]:
# Ordinare un array

arr = np.array([5,2,4,1,3])
print(np.sort(arr))

arr = np.array(["Barbara", "Carlo", "Alessandra"])
print(np.sort(arr))

[1 2 3 4 5]
['Alessandra' 'Barbara' 'Carlo']


### E' anche possibile ordinare un array specificando però che solo alcuni degli elementi devono essere selezionati. Anche questa volta ci serviamo di un filtro.

In [64]:
# Filtrare i soli elementi pari dell'array

arr = np.array([5,2,4,1,3])
filtro = arr%2 == 0
print(arr[filtro])

[2 4]


## 12. Creare un array contenente dati randomici

### Ci serviremo della libreria "random".

In [65]:
from numpy import random

In [66]:
# Creare un array che contiene numeri random compresi tra 0 e 100

arr = random.randint(100, size=(5))
print(arr)

arr = random.randint(100, size=(2,5))
print(arr)

[30 89 25 32 74]
[[66 80 41 71 43]
 [45 77 86 98 48]]


In [67]:
# Scegliere un elemento randomico dall'array

arr = np.array([1,2,3,4,5,6,7,8])
print(random.choice(arr))
print(random.choice(arr, size=(3)))

8
[3 3 5]


In [68]:
# Scegliere un elemento randomico dall'array, stabilendo una personale distribuzione di probabilità

arr = np.array([1,2,3,4,5])
prob = np.array([0.1, 0.2, 0.5, 0.1, 0.1])
print(random.choice(arr, p=prob, size=(15)))

[1 4 3 2 1 4 2 1 3 2 2 5 3 3 5]


### In modo randomico possiamo anche rimescolare gli elementi di un array utilizzando il metodo "shuffle".

In [69]:
# Rimescolare un array con "shuffle"

arr = np.array([1,2,3,4,5,6,7])
random.shuffle(arr)
print(arr)

[6 1 5 7 4 2 3]


### Oltre a "shuffle" è possibile utilizzare "permutation". La differenza è che "shuffle" agisce direttamente sul nostro array mentre invece "permutation" crea un nuovo array lasciando intatto l'originale.

In [70]:
# Rimescolare un array con permutation

arr = np.array([1,2,3,4,5,6,7])
arr2 = random.permutation(arr)
print(arr2)

[4 3 7 6 1 2 5]


## 13. ufunc: definire una funzione personalizzata

### Abbiamo la possibilità di creare delle funzioni che modificano il nostro array. Saremo noi a decidere il comportamento di queste funzioni: potremo specificare che operazione andrà eseguita su ogni elemento dell'array.

In [71]:
def addCinque(x):
    return x+5

# Registriamo la funzione
addCinque = np.frompyfunc(addCinque, 1, 1)

print(addCinque(np.array([1,2,3])))
print(addCinque([1,2,3]))

[6 7 8]
[6 7 8]


### Registrare la funzione è fondamentale poiché in questo modo quando gli passiamo una lista questa verrà convertita in un NumPy array. Ricorda che di default non si possono eseguire operazioni matematiche sugli elementi della lista (come abbiamo visto nella sezione 3 del notebook). La conversione in NumPy array ci semplifica di molto le cose.

### Altre funzioni come np.add, np.multiply, np.divide, np.power, np.ceil, np.floor ecc. ci consentono fi fornire in input delle liste che verranno poi trattate come NumPy array.

In [72]:
lista1 = [1,2,3,4]
lista2 = [5,6,7,8]
somma = np.add(lista1, lista2)
print(somma)

[ 6  8 10 12]
